import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import { Footer, Header, ChakraWrapper } from "@/components";

const roboto = Roboto({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <ChakraWrapper>{children}</ChakraWrapper>
        <Footer />
      </body>
    </html>
  );
}
